version: '3.1'
services:
  app:
    image: craftcms/boilerplate
    build:
      context: .
      dockerfile: Dockerfile-02
    ports:
      - 8080:80
    volumes:
      - ./craft:/var/www/html:cached
    links:
      - mysql
    env_file: ./craft/.env
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: SuperPassword123456!
      MYSQL_DATABASE: dev_craftcms
      MYSQL_USER: craftcms
      MYSQL_PASSWORD: SecretPassword
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis
    ports:
     - 6379:6379
volumes:
  db_data: