version: '3.3'
services:
  app:
    depends_on:
      - db
    image: craftcms/boilerplate
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5600:80
    volumes:
      - .:/var/www/html:cached
    env_file: ./craft/.env
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootCraft
      MYSQL_DATABASE: craft
      MYSQL_USER: craft
      MYSQL_PASSWORD: craft
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis
    ports:
     - 6379:6379
volumes:
  db_data: