version: "3.6"
services:
  php-fpm:
    image: craftcms/php-fpm:7.4-dev
    volumes:
      - .:/app
    links:
      - mysql
    environment:
      ENVIRONMENT: "dev"
      DB_DRIVER: "mysql"
      DB_SERVER: mysql:3306
      DB_PORT: "3306"
      DB_DATABASE: "dev_craftcms"
      DB_USER: "craftcms"
      DB_PASSWORD: "SecretPassword"
      DB_SCHEMA: "public"
      DB_TABLE_PREFIX: ""
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
  console:
    image: craftcms/cli:7.4-dev
    volumes:
      - .:/app
    env_file: .env
    command: ["./craft", "queue/listen"]
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: SuperPassword123456!
      MYSQL_DATABASE: dev_craftcms
      MYSQL_USER: craftcms
      MYSQL_PASSWORD: SecretPassword
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
volumes:
  db_data: